title: Alicia Sabatino # your name (or website title) here
logo: "https://i.etsystatic.com/iusa/512785/68241563/iusa_400x400.68241563_91hl.jpg?version=0" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Alicia's Github 
  <br><br>
  Environmental Science and Geography Major and Computer Science minor 
  <br><br>
  <a href="https://www.twitter.com/nerdjpg">View My Twitter</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
